name = "clean"
uuid = "33a1c499-97fe-4b8f-87d8-dde9826c6ee2"
authors = ["Jack Hanslope <code@jackhanslope.com> and contributors"]
version = "0.1.0"

[deps]
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
